name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check directory structure
        run: |
          echo "Current working directory: $(pwd)"
          ls -la
          if [ -d "midway-project" ]; then
            echo "Contents of midway-project:"
            ls -la midway-project
          else
            echo "midway-project directory does NOT exist!"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd midway-project
          npm install

      - name: Run tests
        run: |
          cd midway-project
          npm test

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
